name: Hassfest Validation

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  hassfest_validation:
    name: Hassfest Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Hassfest Action
        uses: home-assistant/actions/hassfest@master
